
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG # Debug logging for Spring web components
    com.your-application-package: DEBUG # Debug logging for your own application code
    org.hibernate: DEBUG # Debug logging for Hibernate
